language: c
dist: bionic
compiler:
  - gcc
  - clang
sudo: false
addons:
  apt:
    packages:
      - flex
      - bison
      - libsqlite3-dev
      - libsctp-dev
      - libradcli-dev
      - libhiredis-dev
      - unixodbc-dev
      - libconfuse-dev
      - libmysqlclient-dev
      - libexpat1-dev
      - libxml2-dev
      - libpq-dev
      - zlib1g-dev
      - libperl-dev
      - libsnmp-dev
      - libdb-dev
      - libldap2-dev
      - libcurl4-gnutls-dev
      - libgeoip-dev
      - libpcre3-dev
      - libmemcached-dev
      - libmicrohttpd-dev
      - librabbitmq-dev
      - liblua5.1-0-dev
      - libncurses5-dev
      - libjson0-dev
      - uuid-dev
#      - libjwt-dev
script: CC_EXTRA_OPTS=-Werror FASTER=1 NICER=0 make \
  exclude_modules="db_oracle osp sngtc cachedb_cassandra cachedb_couchbase cachedb_mongodb auth_jwt" all
notifications:
  irc:
    channels:
      - "chat.freenode.net#opensips"
    on_success: change
    on_failure: always
  slack:
    secure: MnRvw68QpJHUSZ/IRGUlAjQ62xs3LtEZ0g3pG7Bms0XotuK+YxmSZh7BgV61utuya295LTvdWZQYiutJ4+iPKdF7Mb1KCzaUbY6nrGaIbqif10CKwfIFRsENMhYUKOXdvg52103GNq3/V3/6PGX7Jtiaox9lHcfRhvljs+cUgSk=
    on_success: change
    on_failure: always
jobs:
  include:
    - name: "Build with GCC @ Ubuntu 16"
      dist: xenial
      compiler: gcc
    - name: "Build with Clang @ Ubuntu 16"
      dist: xenial
      compiler: clang
