language: c
sudo: false
addons:
  apt:
    packages:
      - flex
      - bison
      - libsqlite3-dev
      - libsctp-dev
      - libradcli-dev
      - libhiredis-dev
      - unixodbc-dev
      - libconfuse-dev
      - libmysqlclient-dev
      - libexpat1-dev
      - libxml2-dev
      - libpq-dev
      - zlib1g-dev
      - libperl-dev
      - libsnmp-dev
      - libdb-dev
      - libldap2-dev
      - libcurl4-gnutls-dev
      - libgeoip-dev
      - libpcre3-dev
      - libmemcached-dev
      - libmicrohttpd-dev
      - librabbitmq-dev
      - liblua5.1-0-dev
      - libncurses5-dev
      - libjson-c-dev
      - uuid-dev
#      - libjwt-dev
script: CC_EXTRA_OPTS=-Werror FASTER=1 NICER=0 make \
  exclude_modules="db_oracle osp sngtc cachedb_cassandra cachedb_couchbase cachedb_mongodb auth_jwt" all
notifications:
  irc:
    channels:
      - "chat.freenode.net#opensips"
    on_success: change
    on_failure: always
  slack:
    secure: MnRvw68QpJHUSZ/IRGUlAjQ62xs3LtEZ0g3pG7Bms0XotuK+YxmSZh7BgV61utuya295LTvdWZQYiutJ4+iPKdF7Mb1KCzaUbY6nrGaIbqif10CKwfIFRsENMhYUKOXdvg52103GNq3/V3/6PGX7Jtiaox9lHcfRhvljs+cUgSk=
    on_success: change
    on_failure: always
jobs:
  include:
    - name: "Build with GCC 7 @ Ubuntu 16"
      dist: xenial
      compiler: gcc
    - name: "Build with Clang 7 @ Ubuntu 16"
      dist: xenial
      compiler: clang
    - name: "Build with GCC 7 @ Ubuntu 18"
      dist: bionic
      compiler: gcc
    - name: "Build with GCC 9 @ Ubuntu 18"
      dist: bionic
      compiler: gcc
      env:
        - CC=gcc-9 AR=gcc-ar-9 RANLIB=gcc-ranlib-9
        - GCOV_CMD="gcov-9"
      before_install:
        - sudo apt install software-properties-common
        - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get -y install gcc-9 g++-9
    - name: "Build with Clang 7 @ Ubuntu 18"
      dist: bionic
      compiler: clang
    - name: "Build with Clang 9 @ Ubuntu 18"
      dist: bionic
      compiler: clang
      env:
        - CC=clang-9 AR=llvm-ar-9 RANLIB=llvm-ranlib-9
        - GCOV_CMD="llvm-cov-9 gcov"
      before_install:
        - sudo apt-get -y install clang-9 llvm-9-dev libc++-9-dev libc++abi-9-dev
    - name: "Build with Clang 10 @ Ubuntu 18"
      dist: bionic
      compiler: clang
      env:
        - CC=clang-10 AR=llvm-ar-10 RANLIB=llvm-ranlib-10
        - GCOV_CMD="llvm-cov-10 gcov"
      before_install:
        - sudo apt-get -y install clang-10 llvm-10-dev libc++-10-dev libc++abi-10-dev
