name: CIFuzz
on: [push, pull_request]
jobs:
  Fuzzing:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Fuzzers
      id: build
      uses: sobomax/oss-fuzz/infra/cifuzz/actions/build_fuzzers@opensips
      with:
        oss-fuzz-project-name: 'opensips'
        dry-run: false
        language: c
    - name: Run Fuzzers
      uses: sobomax/oss-fuzz/infra/cifuzz/actions/run_fuzzers@opensips
      with:
        oss-fuzz-project-name: 'opensips'
        fuzz-seconds: 600
        dry-run: false
    - name: Upload Crash
      uses: actions/upload-artifact@v1
      if: failure() && steps.build.outcome == 'success'
      with:
        name: artifacts
        path: ./out/artifacts
